<?php

/**
 * Implements hook_menu().
 */
function pushtape_kickstart_menus_menu() {
  // Getting started
  $items['admin/help'] = array(
    'title' => 'Getting Started',
    'description' => '',
    'page callback' => 'advanced_help_topic_page',
    'page arguments' => array('pushtape_kickstart_help', 'first-steps'),
    'access arguments' => array('view advanced help topic'),
    'file path' => drupal_get_path('module', 'advanced_help'),
    'weight' => -25,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // Site settings
  $items['admin/site-config'] = array(
    'title' => 'Site settings',
    'description' => 'Administer the site configuration.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 100,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // tracks
  $items['admin/pushtape/manage-tracks'] = array(
    'title' => 'tracks',
    'description' => 'Manage tracks.',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/pushtape/tracks'),
    'access arguments' => array('access administration pages'),
    'weight' => -20,
    'parent' => 'admin',
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // tracks > Actions
  $items['admin/pushtape/manage-tracks/actions'] = array(
    'title' => 'Actions',
    'description' => 'tracks actions.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 0,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // tracks > Settings
  $items['admin/pushtape/manage-tracks/settings'] = array(
    'title' => 'Settings',
    'description' => 'tracks settings.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 1,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // tracks > Settings > Categories
  $items['admin/pushtape/manage-tracks/settings/categories'] = array(
    'title' => 'Categories',
    'description' => 'Manage tagging, categorization, and classification of your tracks.',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/pushtape/config/tracks-categories'),
    'access callback' => TRUE,
  );
  // tracks > Settings > track types
  $items['admin/pushtape/manage-tracks/settings/track-types'] = array(
    'title' => 'track types',
    'description' => 'Manage tracks types for your store.',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/pushtape/config/types'),
    'access callback' => TRUE,
  );
  // albums
  $items['admin/pushtape/manage-albums'] = array(
    'title' => 'albums',
    'description' => 'Manage albums.',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/pushtape/albums'),
    'access arguments' => array('access administration pages'),
    'weight' => -15,
    'parent' => 'admin',
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // albums > Actions
  $items['admin/pushtape/manage-albums/actions'] = array(
    'title' => 'Actions',
    'description' => 'albums actions.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 0,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // Content
  $items['admin/pushtape/manage-content'] = array(
    'title' => 'Content',
    'description' => 'Manage content.',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/content'),
    'access arguments' => array('access administration pages'),
    'weight' => -10,
    'parent' => 'admin',
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // Content > Actions
  $items['admin/pushtape/manage-content/actions'] = array(
    'title' => 'Actions',
    'description' => 'Content actions.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 0,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // Content > Settings
  $items['admin/pushtape/manage-content/settings'] = array(
    'title' => 'Settings',
    'description' => 'Content settings.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 1,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // Content > Settings > Content types
  $items['admin/pushtape/manage-content/settings/content-types'] = array(
    'title' => 'Content types',
    'description' => 'Manage content types for your store.',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/pushtape/config/types/content'),
    'access callback' => TRUE,
  );
  // Store settings > Advanced store settings
  $items['admin/pushtape/config/advanced-settings'] = array(
    'title' => 'Advanced store settings',
    'description' => 'Advanced store settings.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 0,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // Store settings > track settings
  $items['admin/pushtape/config/track-settings'] = array(
    'title' => 'track settings',
    'description' => 'Administer the track settings.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 5,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // Site settings > Visual & Layout
  $items['admin/site-config/layout'] = array(
    'title' => 'Visual & Layout',
    'description' => 'Administer the appearance and layout of your store.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 0,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // Site settings > Advanced settings
  $items['admin/site-config/advanced'] = array(
    'title' => 'Advanced settings',
    'description' => 'Administer the site configuration.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 1,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // Store settings > track settings > track types
  $items['admin/pushtape/config/types'] = array(
    'title' => 'track types',
    'description' => 'Manage tracks types for your store.',
    'page callback' => 'pushtape_track_ui_types_overview',
    'access arguments' => array('administer track types'),
    'file' => 'includes/pushtape_track_ui.types.inc',
    'file path' => drupal_get_path('module', 'pushtape_track_ui'),
    'parent' => 'admin/pushtape/config/track-settings',
  );
  $items['admin/pushtape/config/types/track'] = array(
    'title' => 'track types',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );


  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function pushtape_kickstart_menus_menu_alter(&$items) {
  // Move the pages under the "Getting Started" entry.
  foreach (array('admin/help/getting-started', 'admin/help/first-steps', 'admin/demo') as $path) {
    if (isset($items[$path])) {
      $items[$path]['parent'] = 'admin/help';
      $items[$path]['context'] = MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE;
      if ($path == 'admin/demo') {
        $items[$path]['title'] = 'Reset your Demo Site';
      }
    }
  }

  // tracks > Manage tracks
  if (isset($items['admin/pushtape/tracks'])) {
    $items['admin/pushtape/tracks']['parent'] = 'admin/pushtape/manage-tracks/actions';
    $items['admin/pushtape/tracks']['title'] = 'Manage tracks';
    $items['admin/pushtape/tracks']['weight'] = -30;
    $items['admin/pushtape/tracks']['type'] = MENU_NORMAL_ITEM;
  }
  // tracks > Add a track
  if (isset($items['node/add/add-track'])) {
    $items['node/add/add-track']['parent'] = 'admin/pushtape/manage-tracks/actions';
    $items['node/add/add-track']['title'] = 'Add a track';
    $items['node/add/add-track']['type'] |= MENU_NORMAL_ITEM;
  }
  // albums > Manage albums
  if (isset($items['admin/pushtape/albums'])) {
    $items['admin/pushtape/albums']['title'] = 'Manage albums';
    $items['admin/pushtape/albums']['parent'] = 'admin/pushtape/manage-albums/actions';
    $items['admin/pushtape/albums']['weight'] = -25;
  }
  // albums > Add an order
  if (isset($items['admin/pushtape/albums/add'])) {
    $items['admin/pushtape/albums/add']['parent'] = 'admin/pushtape/manage-albums/actions';
    $items['admin/pushtape/albums/add']['title'] = 'Add an order';
    $items['admin/pushtape/albums/add']['weight'] = -24;
  }
  // Content > Manage content
  if (isset($items['admin/content'])) {
    $items['admin/content']['parent'] = 'admin/pushtape/manage-content/actions';
    $items['admin/content']['title'] = 'Manage content';
    $items['admin/content']['weight'] = -15;
    $items['admin/content']['type'] = MENU_NORMAL_ITEM;
  }
  // Content > Manage comments
  if (isset($items['admin/content/comment'])) {
    $items['admin/content/comment']['parent'] = 'admin/pushtape/manage-content/actions';
    $items['admin/content/comment']['title'] = 'Manage comments';
    $items['admin/content/comment']['weight'] = -14;
    $items['admin/content/comment']['type'] = MENU_NORMAL_ITEM;
  }
  // Content > Add content
  if (isset($items['node/add/add-content'])) {
    $items['node/add/add-content']['parent'] = 'admin/pushtape/manage-content/actions';
    $items['node/add/add-content']['title'] = 'Add content';
    $items['node/add/add-content']['type'] |= MENU_NORMAL_ITEM;
  }

  // Disable "Store" entry point.
  if (isset($items['admin/pushtape'])) {
    $items['admin/pushtape']['hidden'] = TRUE;
  }

  // "Store settings" entry point.
  if (isset($items['admin/pushtape/config'])) {
    $items['admin/pushtape/config']['title'] = 'Store settings';
    $items['admin/pushtape/config']['parent'] = 'admin';
    $items['admin/pushtape/config']['weight'] = 50;
    $items['admin/pushtape/config']['options'] = array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    );
  }

  if (isset($items['admin/pushtape/config/track-pricing'])) {
    // Just because the default title 'track pricing rules' is too long.
    $items['admin/pushtape/config/track-pricing']['title'] = 'Pricing rules';
  }

  if (isset($items['admin/pushtape/config/tracks-categories'])) {
    $items['admin/pushtape/config/tracks-categories']['parent'] = 'admin/pushtape/config/track-settings';
  }


  // Move the appearance and layout entries under admin/site-config/layout.
  foreach (array('admin/appearance', 'admin/structure/block', 'admin/structure/views') as $path) {
    if (isset($items[$path])) {
      $items[$path]['parent'] = 'admin/site-config/layout';
    }
  }
  // Move the main Drupal entry points below admin/site-config/advanced.
  foreach (array('admin/structure', 'admin/people', 'admin/modules', 'admin/config', 'admin/reports', 'admin/advanced_help') as $path) {
    if (isset($items[$path])) {
      $items[$path]['parent'] = 'admin/site-config/advanced';
    }
  }
  if (isset($items['admin/pushtape/jirafe'])) {
    $items['admin/pushtape/jirafe']['title'] = 'Dashboard';
    $items['admin/pushtape/jirafe']['parent'] = 'admin';
    $items['admin/pushtape/jirafe']['weight'] = 200;
  }
}

/**
 * Implements hook_init().
 *
 * Alter the page title on the Jirafe dashboard page.
 */
function pushtape_kickstart_menus_init() {
  $item = menu_get_item();
  if ($item['path'] != 'admin/pushtape/jirafe') {
    return;
  }

  drupal_set_title(t('pushtape Guys Dashboard by Jirafe'));
}

/**
 * Implements hook_menu_link_alter().
 *
 * Apply some link configuration stored in the router during the menu
 * rebuild process.
 */
function pushtape_kickstart_menus_menu_link_alter(&$link) {
  // Check if the item belongs to a shortcut menu.
  if (module_exists('shortcut') && shortcut_set_load($link['menu_name'])) {
    // Don't change the plid of shortcut menu items.
    return;
  }

  $item = _pushtape_kickstart_menu_find_router($link['link_path']);
  if ($item && isset($item['options'])) {
    if (!isset($link['options'])) {
      $link['options'] = array();
    }
    $link['options'] += $item['options'];
  }
  if ($item && isset($item['parent'])) {
    $plid = db_query('SELECT mlid FROM {menu_links} WHERE link_path = :path', array(':path' => $item['parent']))->fetchField();
    if ($plid) {
      $link['plid'] = $plid;
    }
  }
}

function _pushtape_kickstart_menu_find_router($link_path) {
  $router = menu_get_router();
  $parts = explode('/', $link_path, MENU_MAX_PARTS);

  $ancestors = menu_get_ancestors($parts);
  // Add an empty router path as a fallback.
  $ancestors[] = '';
  foreach ($ancestors as $key => $router_path) {
    if (isset($router[$router_path])) {
      // Exit the loop leaving $router_path as the first match.
      break;
    }
  }

  return isset($router[$router_path]) ? $router[$router_path] : NULL;
}

/**
 * Implements hook_module_implements_alter().
 */
function pushtape_kickstart_menus_module_implements_alter(&$implementations, $hook) {
  if (in_array($hook, array('menu_alter'))) {
    // Move our hook implementation to the bottom.
    $group = $implementations['pushtape_kickstart_menus'];
    unset($implementations['pushtape_kickstart_menus']);
    $implementations['pushtape_kickstart_menus'] = $group;
  }
}

/**
 * Implements hook_views_api().
 */
function pushtape_kickstart_menus_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'pushtape_kickstart_menus') . '/views',
  );
}

/**
 * Implements hook_menu_breadcrumb_alter().
 */
function pushtape_kickstart_menus_menu_breadcrumb_alter(&$active_trail, $item) {
  // Home > Administration > Store settings > track settings > Content types OR track types
  if (drupal_match_path($item['path'], "admin/structure/types/*\nadmin/pushtape/config/types/*\nadmin/pushtape/tracks/types*")) {
    if (drupal_match_path($item['path'], "admin/structure/types/add\nadmin/pushtape/tracks/types")) {
      return;
    }
    $is_track_type = in_array(strtr(arg(4),'-','_'), array_keys(pushtape_track_reference_node_types()));
    $is_track_type_page = drupal_match_path($item['path'], "admin/pushtape/tracks/types*");
    if ($is_track_type_page) {
      $active_trail_end = array_slice($active_trail, 5);
    }
    else {
      $active_trail_end = array_slice($active_trail, 6);
    }
    $active_trail = array_slice($active_trail, 0, 1);
    $active_trail[] = menu_get_item('admin');
    $active_trail[] = menu_get_item('admin/pushtape/config');
    $active_trail[] = menu_get_item('admin/pushtape/config/track-settings');
    // Append either "track types" OR "Content types".
    if ($is_track_type_page || $is_track_type) {
      if ($is_track_type_page) {
        array_shift($active_trail_end);
      }
      $active_trail[] = menu_get_item('admin/pushtape/config/types');
    }
    else {
      $active_trail[] = menu_get_item('admin/pushtape/config/types/content');
    }
    $active_trail = array_merge($active_trail, $active_trail_end);
  }
  // Home > Administration > Content > Add content OR Add track
  else if (drupal_match_path($item['path'], 'node/add*')) {
    if (drupal_match_path($item['path'], 'node/add/add-track')) {
      return;
    }
    $active_trail_end = array_slice($active_trail, 1);
    $active_trail = array_slice($active_trail, 0, 1);
    $active_trail[] = menu_get_item('admin');
    $is_track_display_page = in_array(strtr(arg(2),'-','_'), array_keys(pushtape_track_reference_node_types()));
    if ($is_track_display_page) {
      array_shift($active_trail_end);
      $active_trail[] = menu_get_item('admin/pushtape/manage-tracks');
      $active_trail[] = menu_get_item('admin/pushtape/manage-tracks/actions');
      $active_trail[] = menu_get_item('node/add/add-track');
    }
    else {
      $active_trail[] = array('title' => 'Content') + menu_get_item('admin/content');
    }
    $active_trail = array_merge($active_trail, $active_trail_end);
  }
}
