<?php

/**
 * Implements hook_menu().
 */
function pushtape_kickstart_menus_menu() {
  // Getting started
  $items['admin/help'] = array(
    'title' => 'Getting Started',
    'description' => '',
    'page callback' => 'advanced_help_topic_page',
    'page arguments' => array('pushtape_kickstart_help', 'first-steps'),
    'access arguments' => array('view advanced help topic'),
    'file path' => drupal_get_path('module', 'advanced_help'),
    'weight' => -25,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );

  // Site settings
  $items['admin/site-config'] = array(
    'title' => 'Site settings',
    'description' => 'Administer the site configuration.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 100,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
/*
  $items['node/add'] = array(
    'title' => 'add',
    'description' => 'add.',
    'page callback' => 'node_add',
    'page arguments' => array('node/add'),
    'access arguments' => array('access administration pages'),
    'weight' => -20,
    'parent' => 'admin',
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
*/
    // @todo Remove this loop when we have a 'description callback' property.
  // Reset internal static cache of _node_types_build(), forces to rebuild the
  // node type information.
 /*
  node_type_cache_reset();
  foreach (node_type_get_types() as $type) {
    $type_url_str = str_replace('_', '-', $type->type);
    $items['node/add/' . $type_url_str] = array(
      'title' => $type->name,
      'title callback' => 'check_plain',
      'parent' => 'node/add',
      'file path' => drupal_get_path('module', 'node'),
      'page callback' => 'node_add',
      'page arguments' => array($type->type),
      'access callback' => 'node_access',
      'access arguments' => array('create', $type->type),
      'description' => $type->description,
      'file' => 'node.pages.inc',
    );
  }

  */
  // Discography
  $items['admin/pushtape/manage-discography'] = array(
    'title' => 'Discography',
    'description' => 'Manage Discography.',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/pushtape/discography'),
    'access arguments' => array('access administration pages'),
    'weight' => -20,
    'parent' => 'admin',
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
// tracks > Actions
  $items['admin/pushtape/manage-discography/actions'] = array(
    'title' => 'Actions',
    'description' => 'tracks actions.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 0,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );


  // tracks > Settings
  $items['admin/pushtape/manage-discography/settings'] = array(
    'title' => 'Settings',
    'description' => 'discography settings.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 1,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // discography > Settings > Categories
  $items['admin/pushtape/manage-discography/settings/categories'] = array(
    'title' => 'Categories',
    'description' => 'Manage tagging, categorization, and classification of your tracks.',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/pushtape/config/tracks-categories'),
    'access callback' => TRUE,
  );
  // tracks > Settings > track types
  $items['admin/pushtape/manage-discography/settings/tracks'] = array(
    'title' => 'Tracks',
    'description' => 'Manage tracks for your Site.',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/pushtape/config/tracks'),
    'access callback' => TRUE,
  );
    // albums > Settings > albums types
  $items['admin/pushtape/manage-discography/settings/albums'] = array(
    'title' => 'Albums',
    'description' => 'Manage albums for your Site.',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/pushtape/config/albums'),
    'access callback' => TRUE,
  );

  // Content
  $items['admin/pushtape/manage-content'] = array(
    'title' => 'Content',
    'description' => 'Manage content.',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/content'),
    'access arguments' => array('access administration pages'),
    'weight' => -10,
    'parent' => 'admin',
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // Content > Actions
  $items['admin/pushtape/manage-content/actions'] = array(
    'title' => 'Actions',
    'description' => 'Content actions.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 0,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // Content > Settings
  $items['admin/pushtape/manage-content/settings'] = array(
    'title' => 'Settings',
    'description' => 'Content settings.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 1,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // Content > Settings > Content types
  $items['admin/pushtape/manage-content/settings/content-types'] = array(
    'title' => 'Content types',
    'description' => 'Manage content types for your Site.',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/structure/types'),
    'access callback' => TRUE,
  );
  // Site settings > Advanced Site settings
  $items['admin/pushtape/config/advanced-settings'] = array(
    'title' => 'Advanced Site settings',
    'description' => 'Advanced Site settings.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 0,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );

  // Site settings > Visual & Layout
  $items['admin/site-config/layout'] = array(
    'title' => 'Visual & Layout',
    'description' => 'Administer the appearance and layout of your Site.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 0,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  // Site settings > Advanced settings
  $items['admin/site-config/advanced'] = array(
    'title' => 'Advanced settings',
    'description' => 'Administer the site configuration.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 1,
    'options' => array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    ),
  );
  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function pushtape_kickstart_menus_menu_alter(&$items) {
  // Move the pages under the "Getting Started" entry.
  foreach (array('admin/help/getting-started', 'admin/help/first-steps', 'admin/demo') as $path) {
    if (isset($items[$path])) {
      $items[$path]['parent'] = 'admin/help';
      $items[$path]['context'] = MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE;
      if ($path == 'admin/demo') {
        $items[$path]['title'] = 'Reset your Demo Site';
      }
    }
  }
//Changing titles
// Content > Manage content
  if (isset($items['admin/content'])) {
    $items['admin/content']['parent'] = 'admin/pushtape/manage-content/actions';
    $items['admin/content']['title'] = 'Manage content';
    $items['admin/content']['weight'] = -15;
    $items['admin/content']['type'] = MENU_NORMAL_ITEM;
  }
  // Content > Manage comments
  if (isset($items['admin/content/comment'])) {
    $items['admin/content/comment']['parent'] = 'admin/pushtape/manage-content/actions';
    $items['admin/content/comment']['title'] = 'Manage comments';
    $items['admin/content/comment']['weight'] = -14;
    $items['admin/content/comment']['type'] = MENU_NORMAL_ITEM;
  }


/*
  // Content > Add content
  if (isset($items['node/add/add-content'])) {
    $items['node/add/add-content']['parent'] = 'admin/pushtape/manage-content/actions';
    $items['node/add/add-content']['title'] = 'Add content';
    $items['node/add/add-content']['type'] |= MENU_NORMAL_ITEM;
  }

  // tracks > Manage tracks
  if (isset($items['admin/pushtape/tracks'])) {
    $items['admin/pushtape/tracks']['parent'] = 'admin/pushtape/manage-tracks/actions';
    $items['admin/pushtape/tracks']['title'] = 'Manage tracks';
    $items['admin/pushtape/tracks']['weight'] = -30;
    $items['admin/pushtape/tracks']['type'] = MENU_NORMAL_ITEM;
  }
  // tracks > Add a track
  if (isset($items['node/add/add-track'])) {
    $items['node/add/add-track']['parent'] = 'admin/pushtape/manage-tracks/actions';
    $items['node/add/add-track']['title'] = 'Add a track';
    $items['node/add/add-track']['type'] |= MENU_NORMAL_ITEM;
  }
  // albums > Manage albums
  if (isset($items['admin/pushtape/albums'])) {
    $items['admin/pushtape/albums']['title'] = 'Manage albums';
    $items['admin/pushtape/albums']['parent'] = 'admin/pushtape/manage-albums/actions';
    $items['admin/pushtape/albums']['weight'] = -25;
  }
  // albums > Add an album
  if (isset($items['admin/pushtape/albums/add'])) {
    $items['admin/pushtape/albums/add']['parent'] = 'admin/pushtape/manage-albums/actions';
    $items['admin/pushtape/albums/add']['title'] = 'Add an album';
    $items['admin/pushtape/albums/add']['weight'] = -24;
  }

  // Disable a menu
  if (isset($items['admin/pushtape'])) {
    $items['admin/pushtape']['hidden'] = TRUE;
  }
*/
  // "Site settings" entry point.
  if (isset($items['admin/pushtape/config'])) {
    $items['admin/pushtape/config']['title'] = 'Site settings';
    $items['admin/pushtape/config']['parent'] = 'admin';
    $items['admin/pushtape/config']['weight'] = 50;
    $items['admin/pushtape/config']['options'] = array(
      'toolbar_expanded' => TRUE,
      'toolbar_break' => TRUE,
    );
  }

  //if (isset($items['admin/pushtape/config/tracks-categories'])) {
 //   $items['admin/pushtape/config/tracks-categories']['parent'] = 'admin/pushtape/config/track-settings';
 // }

  // Move the appearance and layout entries under admin/site-config/layout.
  foreach (array('admin/appearance', 'admin/structure/block', 'admin/structure/views') as $path) {
    if (isset($items[$path])) {
      $items[$path]['parent'] = 'admin/site-config/layout';
    }
  }
  // Move the main Drupal entry points below admin/site-config/advanced.
  foreach (array('admin/structure', 'admin/people', 'admin/modules', 'admin/config', 'admin/reports', 'admin/advanced_help') as $path) {
    if (isset($items[$path])) {
      $items[$path]['parent'] = 'admin/site-config/advanced';
    }
  }
  if (isset($items['admin/dashboard'])) {
    $items['admin/dashboard']['title'] = 'Dashboard';
    $items['admin/dashboard']['parent'] = 'admin';
    $items['admin/dashboard']['weight'] = 200;
  }
}

/**
 * Implements hook_init().
 *
 * Alter the page title on the Jirafe dashboard page.
 */
function pushtape_kickstart_menus_init() {
  /*
  $item = menu_get_item();
  if ($item['path'] != 'admin/pushtape/jirafe') {
    return;
  }

  drupal_set_title(t('pushtape Guys Dashboard by Jirafe'));

  */
  
}

/**
 * Implements hook_menu_link_alter().
 *
 * Apply some link configuration Sited in the router during the menu
 * rebuild process.
 */
function pushtape_kickstart_menus_menu_link_alter(&$link) {
  // Check if the item belongs to a shortcut menu.
  if (module_exists('shortcut') && shortcut_set_load($link['menu_name'])) {
    // Don't change the plid of shortcut menu items.
    return;
  }

  $item = _pushtape_kickstart_menu_find_router($link['link_path']);
  if ($item && isset($item['options'])) {
    if (!isset($link['options'])) {
      $link['options'] = array();
    }
    $link['options'] += $item['options'];
  }
  if ($item && isset($item['parent'])) {
    $plid = db_query('SELECT mlid FROM {menu_links} WHERE link_path = :path', array(':path' => $item['parent']))->fetchField();
    if ($plid) {
      $link['plid'] = $plid;
    }
  }

}

function _pushtape_kickstart_menu_find_router($link_path) {
  $router = menu_get_router();
  $parts = explode('/', $link_path, MENU_MAX_PARTS);

  $ancestors = menu_get_ancestors($parts);
  // Add an empty router path as a fallback.
  $ancestors[] = '';
  foreach ($ancestors as $key => $router_path) {
    if (isset($router[$router_path])) {
      // Exit the loop leaving $router_path as the first match.
      break;
    }
  }
  return isset($router[$router_path]) ? $router[$router_path] : NULL;
}

/**
 * Implements hook_module_implements_alter().
 */
function pushtape_kickstart_menus_module_implements_alter(&$implementations, $hook) {
  if (in_array($hook, array('menu_alter'))) {
    // Move our hook implementation to the bottom.
    $group = $implementations['pushtape_kickstart_menus'];
    unset($implementations['pushtape_kickstart_menus']);
    $implementations['pushtape_kickstart_menus'] = $group;
  }
}

/**
 * Implements hook_views_api().
 */
function pushtape_kickstart_menus_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'pushtape_kickstart_menus') . '/views',
  );
}

/**
 * Implements hook_menu_breadcrumb_alter().
 */
function pushtape_kickstart_menus_menu_breadcrumb_alter(&$active_trail, $item) {
  // Home > Administration > Site settings > track settings > Content types OR track types
 // if (drupal_match_path($item['path'], "admin/structure/types/*")) {
 // }
  // Home > Administration > Content > Add content
 // else if (drupal_match_path($item['path'], 'node/add*')) {

 // }
}
